"""Update table Lesson

Revision ID: 29eb5abcb592
Revises: 0afc3443bb3a
Create Date: 2024-12-07 15:48:45.804291

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "29eb5abcb592"
down_revision: Union[str, None] = "0afc3443bb3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
