"""Update table Lesson, course

Revision ID: 5c461a97aab6
Revises: 5dbda0eaa984
Create Date: 2024-12-21 07:53:35.817133

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c461a97aab6"
down_revision: Union[str, None] = "5dbda0eaa984"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "courses", sa.Column("duration_seconds", sa.Integer(), nullable=False)
    )
    op.add_column(
        "lessons", sa.Column("duration_seconds", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lessons", "duration_seconds")
    op.drop_column("courses", "duration_seconds")
    # ### end Alembic commands ###
