"""Update table Lesson

Revision ID: 0afc3443bb3a
Revises: c39941931188
Create Date: 2024-12-07 14:50:16.432670

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0afc3443bb3a"
down_revision: Union[str, None] = "c39941931188"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lesson_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("video_progress", sa.Float(), nullable=False),
        sa.Column("quiz_completed", sa.Integer(), nullable=False),
        sa.Column("quiz_correct", sa.Integer(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "quizzes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column(
            "quiz_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "lessons", sa.Column("video_url", sa.String(), nullable=True)
    )
    op.drop_column("lessons", "duration")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lessons",
        sa.Column(
            "duration", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("lessons", "video_url")
    op.drop_table("quizzes")
    op.drop_table("lesson_progress")
    # ### end Alembic commands ###
